-- Titles resolve from the setting_id; tooltips from "<setting_id>_description".

-- The game's own term in the player's language, or `fallback` if it does not resolve.
local function game_term(key, fallback)
	if not Localize then
		return fallback
	end
	local text = Localize(key)
	if not text or text == "" or string.sub(text, 1, 1) == "<" then
		return fallback
	end
	return text
end

local PERIL             = game_term("loc_ranged_warp_charge", "Peril")
local RELOAD            = game_term("loc_ingame_weapon_reload", "Reload")
local SCRIERS_GAZE      = game_term("loc_talent_psyker_combat_ability_overcharge_stance", "Scrier's Gaze")
local CRYSTALLINE_WILL  = game_term("loc_talent_psyker_alternative_peril_explosion", "Crystalline Will")
local BLITZ             = game_term("loc_tactical_overlay_build_blitz", "Blitz")
local PSYKINETICS_WRATH = game_term("loc_talent_psyker_2_combat", "Psykinetic's Wrath")
local VENTING_SHRIEK    = game_term("loc_talent_psyker_shout_vent_warp_charge", "Venting Shriek")
local WARP_UNBOUND      = game_term("loc_talent_psyker_overcharge_infinite_casting", "Warp Unbound")

local LANGUAGES = { "en", "de", "es", "fr", "it", "pl", "ru", "ja", "ko", "pt-br", "zh-cn", "zh-tw" }

-- Indicator words, also the word dropdowns' defaults.
local TXT_SAFE = {
	en = "SAFE", de = "SICHER", es = "SEGURO", fr = "SÛR", it = "SICURO", pl = "BEZPIECZNIE",
	ru = "БЕЗОПАСНО", ja = "安全", ko = "안전", ["pt-br"] = "SEGURO", ["zh-cn"] = "安全", ["zh-tw"] = "安全",
}
local TXT_UNSAFE = {
	en = "UNSAFE", de = "UNSICHER", es = "PELIGRO", fr = "DANGER", it = "PERICOLO", pl = "NIEBEZPIECZNIE",
	ru = "ОПАСНО", ja = "危険", ko = "위험", ["pt-br"] = "PERIGO", ["zh-cn"] = "危险", ["zh-tw"] = "危險",
}

local WORD_DEFAULT = {
	en = "Default", de = "Standard", es = "Predeterminado", fr = "Défaut", it = "Predefinito",
	pl = "Domyślnie", ru = "По умолчанию", ja = "既定値", ko = "기본값", ["pt-br"] = "Padrão",
	["zh-cn"] = "默认", ["zh-tw"] = "預設",
}
local WORD_ON = {
	en = "On", de = "An", es = "Activado", fr = "Activé", it = "Attivo", pl = "Wł.",
	ru = "Вкл.", ja = "オン", ko = "켜짐", ["pt-br"] = "Ligado", ["zh-cn"] = "开启", ["zh-tw"] = "開啟",
}
local WORD_OFF = {
	en = "Off", de = "Aus", es = "Desactivado", fr = "Désactivé", it = "Disattivo", pl = "Wył.",
	ru = "Выкл.", ja = "オフ", ko = "꺼짐", ["pt-br"] = "Desligado", ["zh-cn"] = "关闭", ["zh-tw"] = "關閉",
}
local WORD_REACTIVE = {
	en = "Reactive", de = "Reaktiv", es = "Reactivo", fr = "Réactif", it = "Reattivo", pl = "Reaktywny",
	ru = "Реактивно", ja = "リアクティブ", ko = "반응형", ["pt-br"] = "Reativo", ["zh-cn"] = "响应式", ["zh-tw"] = "回應式",
}
local WORD_PROACTIVE = {
	en = "Proactive", de = "Proaktiv", es = "Proactivo", fr = "Proactif", it = "Proattivo", pl = "Proaktywny",
	ru = "Проактивно", ja = "プロアクティブ", ko = "선제형", ["pt-br"] = "Proativo", ["zh-cn"] = "主动式", ["zh-tw"] = "主動式",
}
local WORD_RELAXED = {
	en = "Relaxed", de = "Locker", es = "Relajado", fr = "Souple", it = "Permissivo", pl = "Luźny",
	ru = "Гибкий", ja = "緩和", ko = "완화", ["pt-br"] = "Relaxado", ["zh-cn"] = "宽松", ["zh-tw"] = "寬鬆",
}

-- Appends "(Default = X)" to each tooltip. `default` is a string or a per-language table.
local function with_default(default, translations)
	local out = {}
	for i = 1, #LANGUAGES do
		local lang = LANGUAGES[i]
		local value = type(default) == "table" and (default[lang] or default.en) or default
		local suffix = string.format("(%s = %s)", WORD_DEFAULT[lang] or WORD_DEFAULT.en, value)
		local text = translations[lang]
		out[lang] = text and (text .. " " .. suffix) or suffix
	end
	return out
end

return {
	mod_name = {
		en = "No More Overloads",
		de = "No More Overloads",
		es = "No More Overloads",
		fr = "No More Overloads",
		it = "No More Overloads",
		pl = "No More Overloads",
		ru = "No More Overloads",
		ja = "No More Overloads",
		ko = "No More Overloads",
		["pt-br"] = "No More Overloads",
		["zh-cn"] = "No More Overloads",
		["zh-tw"] = "No More Overloads",
	},
	mod_description = {
		en = string.format("Psyker anti-overload assistant. Blocks the %s actions that would trigger an Overload, warns on the HUD, and can quell %s or use %s / %s / %s for you.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		de = string.format("Psyker-Überladungsschutz. Blockiert die %s-Aktionen, die eine Überladung auslösen würden, warnt im HUD und kann für dich %s entladen oder %s / %s / %s einsetzen.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		es = string.format("Asistente antisobrecarga para el Psyker. Bloquea las acciones de %s que provocarían una Sobrecarga, avisa en el HUD y puede sofocar %s o usar %s / %s / %s por ti.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		fr = string.format("Assistant anti-surcharge pour le Psyker. Bloque les actions de %s qui déclencheraient une Surcharge, alerte sur l'ATH et peut apaiser le %s ou utiliser %s / %s / %s à votre place.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		it = string.format("Assistente anti-sovraccarico per lo Psyker. Blocca le azioni di %s che causerebbero un Sovraccarico, avvisa sull'HUD e può sfogare il %s o usare %s / %s / %s al posto tuo.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		pl = string.format("Asystent antyprzeciążeniowy dla Psykera. Blokuje akcje %s, które wywołałyby przeciążenie, ostrzega na HUD-zie i może za ciebie wygasić %s lub użyć %s / %s / %s.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ru = string.format("Помощник против перегрузки для Псайкера. Блокирует действия %s, которые вызвали бы перегрузку, предупреждает в интерфейсе и может усмирить %s или применить %s / %s / %s за вас.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ja = string.format("サイカー用オーバーロード防止アシスト。オーバーロードを引き起こす%sアクションをブロックし、HUD で警告し、代わりに%sのクエルや%s/%s/%sの発動も行えます。", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ko = string.format("사이커용 과부하 방지 도우미. 과부하를 유발하는 %s 행동을 차단하고, HUD로 경고하며, 대신 %s를 진정하거나 %s / %s / %s를 사용할 수 있습니다.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["pt-br"] = string.format("Assistente anti-sobrecarga para o Psyker. Bloqueia as ações de %s que causariam uma Sobrecarga, avisa na interface e pode dissipar %s ou usar %s / %s / %s por você.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["zh-cn"] = string.format("灵能者防过载助手。拦截会触发过载的%s动作，在抬头界面上警告，并可代你平息%s或发动%s/%s/%s。", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["zh-tw"] = string.format("靈能者防過載助手。攔截會觸發超載的%s動作，在 HUD 上警告，並可代你平息%s或發動%s/%s/%s。", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
	},

	txt_safe = TXT_SAFE,
	txt_unsafe = TXT_UNSAFE,

	-- Groups
	group_blocking = {
		en = "Input Blocking",
		de = "Eingabe-Blockierung",
		es = "Bloqueo de entradas",
		fr = "Blocage des entrées",
		it = "Blocco degli input",
		pl = "Blokowanie wejść",
		ru = "Блокировка ввода",
		ja = "入力ブロック",
		ko = "입력 차단",
		["pt-br"] = "Bloqueio de entrada",
		["zh-cn"] = "输入拦截",
		["zh-tw"] = "輸入攔截",
	},
	group_smart_triggers = {
		en = "Auto Recovery",
		de = "Automatische Rettung",
		es = "Recuperación automática",
		fr = "Récupération auto",
		it = "Recupero automatico",
		pl = "Automatyczne ratowanie",
		ru = "Автоматическое спасение",
		ja = "自動リカバリー",
		ko = "자동 회복",
		["pt-br"] = "Recuperação automática",
		["zh-cn"] = "自动自救",
		["zh-tw"] = "自動自救",
	},
	group_indicator = {
		en = "HUD Indicator",
		de = "HUD-Anzeige",
		es = "Indicador del HUD",
		fr = "Indicateur ATH",
		it = "Indicatore HUD",
		pl = "Wskaźnik HUD",
		ru = "Индикатор интерфейса",
		ja = "HUD 表示",
		ko = "HUD 표시기",
		["pt-br"] = "Indicador da interface",
		["zh-cn"] = "抬头界面指示器",
		["zh-tw"] = "HUD 指示器",
	},

	-- Input Blocking
	blocking_type = {
		en = "Blocking type",
		de = "Blockiertyp",
		es = "Tipo de bloqueo",
		fr = "Type de blocage",
		it = "Tipo di blocco",
		pl = "Typ blokowania",
		ru = "Тип блокировки",
		ja = "ブロックの種類",
		ko = "차단 유형",
		["pt-br"] = "Tipo de bloqueio",
		["zh-cn"] = "拦截类型",
		["zh-tw"] = "攔截類型",
	},
	blocking_type_description = with_default(WORD_RELAXED, {
		en = "Strict blocks every action that would trigger an Overload. Relaxed allows one while your recovery ability is off cooldown, so you can start an Overload and recover.",
		de = "Streng blockiert jede Aktion, die eine Überladung auslösen würde. Locker erlaubt eine, solange deine Rettungsfähigkeit bereit ist, sodass du eine Überladung beginnen und dich retten kannst.",
		es = "Estricto bloquea toda acción que provocaría una Sobrecarga. Relajado permite una mientras tu habilidad de recuperación esté lista, para que puedas iniciar una Sobrecarga y recuperarte.",
		fr = "Strict bloque toute action qui déclencherait une Surcharge. Souple en autorise une tant que votre capacité de secours est disponible, pour que vous puissiez déclencher une Surcharge et vous rétablir.",
		it = "Rigido blocca ogni azione che causerebbe un Sovraccarico. Permissivo ne consente uno finché la tua abilità di recupero è pronta, così puoi avviare un Sovraccarico e recuperare.",
		pl = "Ścisły blokuje każdą akcję, która wywołałaby przeciążenie. Luźny pozwala na nie, gdy twoja zdolność ratunkowa jest gotowa, więc możesz zacząć przeciążenie i się uratować.",
		ru = "Строгий блокирует любое действие, которое вызвало бы перегрузку. Гибкий разрешает её, пока способность спасения готова, чтобы вы могли начать перегрузку и восстановиться.",
		ja = "厳格はオーバーロードを引き起こすあらゆるアクションをブロックします。緩和は救援アビリティがクールダウン中でなければオーバーロードを許可し、あえて始めてから立て直せます。",
		ko = "엄격은 과부하를 유발하는 모든 행동을 차단합니다. 완화는 회복 능력이 준비되어 있으면 과부하를 허용하여, 일부러 시작한 뒤 회복할 수 있습니다.",
		["pt-br"] = "Estrito bloqueia toda ação que causaria uma Sobrecarga. Relaxado permite uma enquanto sua habilidade de recuperação está pronta, para você iniciar uma Sobrecarga e se recuperar.",
		["zh-cn"] = "严格会拦截任何会触发过载的动作。宽松则在你的救援技能冷却完毕时允许过载，让你可以主动开始再恢复。",
		["zh-tw"] = "嚴格會攔截任何會觸發超載的動作。寬鬆則在你的救援技能冷卻完畢時允許過載，讓你可以主動開始再恢復。",
	}),
	opt_blocking_strict = {
		en = "Strict", de = "Streng", es = "Estricto", fr = "Strict", it = "Rigido", pl = "Ścisły",
		ru = "Строгий", ja = "厳格", ko = "엄격", ["pt-br"] = "Estrito", ["zh-cn"] = "严格", ["zh-tw"] = "嚴格",
	},
	opt_blocking_relaxed = WORD_RELAXED,
	block_staffs = {
		en = "Block Force Staffs",
		de = "Psistäbe blockieren",
		es = "Bloquear Báculos de fuerza",
		fr = "Bloquer les Bâtons de force",
		it = "Blocca i Bastoni psichici",
		pl = "Blokuj Laski psioniczne",
		ru = "Блокировать психосиловые посохи",
		ja = "フォースの杖をブロック",
		ko = "포스 지팡이 차단",
		["pt-br"] = "Bloquear Cajados de força",
		["zh-cn"] = "拦截力场杖",
		["zh-tw"] = "攔截力場法杖",
	},
	block_staffs_description = with_default(WORD_ON, {}),
	block_blitzes = {
		en = string.format("Block %s", BLITZ),
		de = string.format("%s blockieren", BLITZ),
		es = string.format("Bloquear %s", BLITZ),
		fr = string.format("Bloquer le %s", BLITZ),
		it = string.format("Blocca il %s", BLITZ),
		pl = string.format("Blokuj %s", BLITZ),
		ru = string.format("Блокировать %s", BLITZ),
		ja = string.format("%sをブロック", BLITZ),
		ko = string.format("%s 차단", BLITZ),
		["pt-br"] = string.format("Bloquear %s", BLITZ),
		["zh-cn"] = string.format("拦截%s", BLITZ),
		["zh-tw"] = string.format("攔截%s", BLITZ),
	},
	block_blitzes_description = with_default(WORD_ON, {}),
	block_force_swords = {
		en = "Block Force Swords",
		de = "Psischwerter blockieren",
		es = "Bloquear Espadas de fuerza",
		fr = "Bloquer les Épées de force",
		it = "Blocca le Spade psichiche",
		pl = "Blokuj Miecze psioniczne",
		ru = "Блокировать психосиловые мечи",
		ja = "フォースソードをブロック",
		ko = "포스 검 차단",
		["pt-br"] = "Bloquear Espadas de força",
		["zh-cn"] = "拦截力场剑",
		["zh-tw"] = "攔截力場劍",
	},
	block_force_swords_description = with_default(WORD_ON, {}),
	block_duelling_swords = {
		en = "Block Duelling Swords",
		de = "Duellschwerter blockieren",
		es = "Bloquear espadas de duelo",
		fr = "Bloquer les épées de duel",
		it = "Blocca le spade da duello",
		pl = "Blokuj miecze pojedynkowe",
		ru = "Блокировать дуэльные мечи",
		ja = "決闘用剣をブロック",
		ko = "결투용 검 차단",
		["pt-br"] = "Bloquear espadas de duelo",
		["zh-cn"] = "拦截决斗剑",
		["zh-tw"] = "攔截決鬥劍",
	},
	block_duelling_swords_description = with_default(WORD_ON, {}),
	block_guns = {
		en = "Block Laspistols",
		de = "Laserpistolen blockieren",
		es = "Bloquear Pistolas láser",
		fr = "Bloquer les Pistolets laser",
		it = "Blocca le Pistole laser",
		pl = "Blokuj Pistolety laserowe",
		ru = "Блокировать лазпистолеты",
		ja = "ラスピストルをブロック",
		ko = "레이저 피스톨 차단",
		["pt-br"] = "Bloquear Pistolas de laser",
		["zh-cn"] = "拦截激光手枪",
		["zh-tw"] = "攔截鐳射手槍",
	},
	block_guns_description = with_default(WORD_ON, {}),
	block_plasma = {
		en = "Block Plasma Guns (any class)",
		de = "Plasmagewehre blockieren (jede Klasse)",
		es = "Bloquear armas de plasma (cualquier clase)",
		fr = "Bloquer les fusils à plasma (toute classe)",
		it = "Blocca i fucili al plasma (qualsiasi classe)",
		pl = "Blokuj karabiny plazmowe (dowolna klasa)",
		ru = "Блокировать плазмомёты (любой класс)",
		ja = "プラズマガンをブロック（全クラス）",
		ko = "플라즈마 건 차단 (모든 직업)",
		["pt-br"] = "Bloquear armas de plasma (qualquer classe)",
		["zh-cn"] = "拦截等离子枪（所有职业）",
		["zh-tw"] = "攔截電漿槍（所有職業）",
	},
	block_plasma_description = with_default(WORD_ON, {
		en = "Blocks the fire at maximum heat so a Plasma Gun can't self-detonate. Works on any class; bracing and venting still work.",
		de = "Blockiert bei maximaler Hitze den Schuss, damit ein Plasmagewehr sich nicht selbst sprengt. Für jede Klasse; Anlegen und Entlüften funktionieren weiter.",
		es = "Bloquea el disparo con el calor al máximo para que un arma de plasma no se autodetone. Cualquier clase; apuntar y ventilar siguen funcionando.",
		fr = "Bloque le tir à chaleur maximale pour qu'un fusil à plasma ne s'autodétruise pas. Toute classe ; visée et purge restent possibles.",
		it = "Blocca il fuoco a calore massimo così un fucile al plasma non si autodistrugge. Qualsiasi classe; mira e sfiato funzionano ancora.",
		pl = "Blokuje strzał przy maksymalnym przegrzaniu, by karabin plazmowy się nie wysadził. Dowolna klasa; celowanie i wentylacja działają.",
		ru = "Блокирует выстрел при максимальном перегреве, чтобы плазмомёт не взорвался. Любой класс; прицеливание и стравливание работают.",
		ja = "最大ヒート時の射撃を止め、プラズマガンの自爆を防ぎます。全クラス対応。構えとベントは通常どおり使えます。",
		ko = "최대 과열 상태의 발사를 막아 플라즈마 건의 자폭을 방지합니다. 모든 직업; 견착과 배출은 그대로 작동합니다.",
		["pt-br"] = "Bloqueia o disparo com o calor no máximo para uma arma de plasma não se autodestruir. Qualquer classe; mirar e ventilar continuam funcionando.",
		["zh-cn"] = "在过热达到上限时拦截开火，防止等离子枪自爆。适用于所有职业；仍可举枪和散热。",
		["zh-tw"] = "在過熱達到上限時攔截開火，防止電漿槍自爆。適用於所有職業；仍可舉槍和散熱。",
	}),
	block_crystalline = {
		en = string.format("Block %s overloads", CRYSTALLINE_WILL),
		de = string.format("%s-Überladungen blockieren", CRYSTALLINE_WILL),
		es = string.format("Bloquear sobrecargas con %s", CRYSTALLINE_WILL),
		fr = string.format("Bloquer les surcharges avec %s", CRYSTALLINE_WILL),
		it = string.format("Blocca i sovraccarichi con %s", CRYSTALLINE_WILL),
		pl = string.format("Blokuj przeciążenia z %s", CRYSTALLINE_WILL),
		ru = string.format("Блокировать перегрузку с %s", CRYSTALLINE_WILL),
		ja = string.format("%sのオーバーロードをブロック", CRYSTALLINE_WILL),
		ko = string.format("%s 과부하 차단", CRYSTALLINE_WILL),
		["pt-br"] = string.format("Bloquear sobrecargas com %s", CRYSTALLINE_WILL),
		["zh-cn"] = string.format("拦截%s的过载", CRYSTALLINE_WILL),
		["zh-tw"] = string.format("攔截%s的超載", CRYSTALLINE_WILL),
	},
	block_crystalline_description = with_default(WORD_OFF, {
		en = string.format("%s makes overload non-lethal, so by default these casts are left alone for self-explode builds. Turn this on to block them like any other overload. The indicator still warns either way.", CRYSTALLINE_WILL),
		de = string.format("%s macht die Überladung nicht tödlich, daher bleiben diese Aktionen standardmäßig unangetastet, damit Selbstexplosions-Builds funktionieren. Aktiviere dies, um sie wie jede andere Überladung zu blockieren. Die Anzeige warnt weiterhin.", CRYSTALLINE_WILL),
		es = string.format("%s hace que la sobrecarga no sea letal, así que por defecto estos lanzamientos se dejan pasar para las builds de autoexplosión. Actívalo para bloquearlos como cualquier otra sobrecarga. El indicador sigue avisando igualmente.", CRYSTALLINE_WILL),
		fr = string.format("%s rend la surcharge non létale ; par défaut, ces actions sont donc laissées passer pour les builds d'auto-explosion. Activez ceci pour les bloquer comme toute autre surcharge. L'indicateur alerte quand même.", CRYSTALLINE_WILL),
		it = string.format("%s rende il sovraccarico non letale, quindi per impostazione predefinita queste azioni vengono lasciate passare per le build ad autoesplosione. Attivalo per bloccarle come qualsiasi altro sovraccarico. L'indicatore avvisa comunque.", CRYSTALLINE_WILL),
		pl = string.format("%s sprawia, że przeciążenie nie jest śmiertelne, więc domyślnie te akcje są przepuszczane dla buildów z samowysadzaniem. Włącz to, aby blokować je jak każde inne przeciążenie. Wskaźnik i tak ostrzega.", CRYSTALLINE_WILL),
		ru = string.format("С %s перегрузка не смертельна, поэтому по умолчанию эти действия пропускаются для билдов с самоподрывом. Включите, чтобы блокировать их как любую другую перегрузку. Индикатор всё равно предупреждает.", CRYSTALLINE_WILL),
		ja = string.format("%sがあればオーバーロードは致命的ではないため、既定ではこれらのアクションは自爆ビルドのためにそのまま通します。オンにすると他のオーバーロードと同様にブロックします。インジケーターはどちらの場合も警告します。", CRYSTALLINE_WILL),
		ko = string.format("%s이 있으면 과부하가 치명적이지 않으므로 기본적으로 이러한 시전은 자폭 빌드를 위해 그대로 둡니다. 켜면 다른 과부하처럼 차단합니다. 표시기는 어느 경우든 계속 경고합니다.", CRYSTALLINE_WILL),
		["pt-br"] = string.format("%s torna a sobrecarga não letal, então por padrão essas ações são deixadas passar para builds de autoexplosão. Ative para bloqueá-las como qualquer outra sobrecarga. O indicador avisa de qualquer forma.", CRYSTALLINE_WILL),
		["zh-cn"] = string.format("%s让过载不致命，因此默认会放行这些动作以支持自爆流派。开启后会像其他过载一样拦截它们。指示器仍会警告。", CRYSTALLINE_WILL),
		["zh-tw"] = string.format("%s讓超載不致命，因此預設會放行這些動作以支援自爆流派。開啟後會像其他超載一樣攔截它們。指示器仍會警告。", CRYSTALLINE_WILL),
	}),

	-- Auto Recovery
	auto_ability = {
		en = "Auto ability use",
		de = "Automatischer Fähigkeitseinsatz",
		es = "Uso automático de habilidad",
		fr = "Utilisation auto de la capacité",
		it = "Uso automatico dell'abilità",
		pl = "Automatyczne użycie zdolności",
		ru = "Автоприменение способности",
		ja = "アビリティ自動使用",
		ko = "능력 자동 사용",
		["pt-br"] = "Uso automático de habilidade",
		["zh-cn"] = "自动使用技能",
		["zh-tw"] = "自動使用技能",
	},
	auto_ability_description = with_default(WORD_ON, {
		en = string.format("Automatically use your recovery ability the moment it is ready while %s is at maximum, to stop the Overload. Choose which abilities below.", PERIL),
		de = string.format("Setzt deine Rettungsfähigkeit automatisch ein, sobald sie bereit ist, während dein %s am Maximum ist, um die Überladung zu stoppen. Wähle unten, welche.", PERIL),
		es = string.format("Usa tu habilidad de recuperación automáticamente en cuanto esté lista mientras tu %s está al máximo, para detener la Sobrecarga. Elige cuáles abajo.", PERIL),
		fr = string.format("Utilise automatiquement votre capacité de secours dès qu'elle est prête tant que votre %s est au maximum, pour stopper la Surcharge. Choisissez lesquelles ci-dessous.", PERIL),
		it = string.format("Usa automaticamente la tua abilità di recupero appena è pronta mentre il tuo %s è al massimo, per fermare il Sovraccarico. Scegli quali sotto.", PERIL),
		pl = string.format("Automatycznie używa twojej zdolności ratunkowej, gdy tylko jest gotowa, gdy twój %s jest na maksimum, aby zatrzymać przeciążenie. Wybierz poniżej które.", PERIL),
		ru = string.format("Автоматически применяет вашу способность спасения, как только она готова, пока ваш %s на максимуме, чтобы остановить перегрузку. Выберите ниже, какие.", PERIL),
		ja = string.format("%sが最大のとき、救援アビリティが使用可能になった瞬間に自動で発動し、オーバーロードを止めます。どのアビリティを使うかは下で選べます。", PERIL),
		ko = string.format("%s이 최대일 때 회복 능력이 준비되는 즉시 자동으로 발동하여 과부하를 막습니다. 어떤 능력을 쓸지는 아래에서 선택하세요.", PERIL),
		["pt-br"] = string.format("Usa sua habilidade de recuperação automaticamente assim que estiver pronta enquanto seu %s estiver no máximo, para deter a Sobrecarga. Escolha quais abaixo.", PERIL),
		["zh-cn"] = string.format("当%s达到上限时，救援技能一就绪便自动发动以阻止过载。在下方选择使用哪些技能。", PERIL),
		["zh-tw"] = string.format("當%s達到上限時，救援技能一就緒便自動發動以阻止超載。在下方選擇使用哪些技能。", PERIL),
	}),
	auto_use_scriers = {
		en = string.format("Auto-use %s", SCRIERS_GAZE),
		de = string.format("%s automatisch einsetzen", SCRIERS_GAZE),
		es = string.format("Usar %s automáticamente", SCRIERS_GAZE),
		fr = string.format("Utiliser %s automatiquement", SCRIERS_GAZE),
		it = string.format("Usa %s automaticamente", SCRIERS_GAZE),
		pl = string.format("Automatycznie używaj %s", SCRIERS_GAZE),
		ru = string.format("Автоприменение: %s", SCRIERS_GAZE),
		ja = string.format("%sを自動使用", SCRIERS_GAZE),
		ko = string.format("%s 자동 사용", SCRIERS_GAZE),
		["pt-br"] = string.format("Usar %s automaticamente", SCRIERS_GAZE),
		["zh-cn"] = string.format("自动使用%s", SCRIERS_GAZE),
		["zh-tw"] = string.format("自動使用%s", SCRIERS_GAZE),
	},
	auto_use_scriers_description = with_default(WORD_ON, {
		en = string.format("Automatically fire %s the moment it is ready while %s is at maximum, to stop the Overload.", SCRIERS_GAZE, PERIL),
		de = string.format("Setzt %s automatisch ein, sobald es bereit ist, während %s am Maximum ist, um die Überladung zu stoppen.", SCRIERS_GAZE, PERIL),
		es = string.format("Usa %s automáticamente en cuanto esté lista mientras %s está al máximo, para detener la Sobrecarga.", SCRIERS_GAZE, PERIL),
		fr = string.format("Utilise %s automatiquement dès qu'elle est prête tant que %s est au maximum, pour stopper la Surcharge.", SCRIERS_GAZE, PERIL),
		it = string.format("Usa %s automaticamente appena è pronta mentre %s è al massimo, per fermare il Sovraccarico.", SCRIERS_GAZE, PERIL),
		pl = string.format("Automatycznie używa %s, gdy tylko jest gotowe, gdy %s jest na maksimum, aby zatrzymać przeciążenie.", SCRIERS_GAZE, PERIL),
		ru = string.format("Автоматически применяет %s, как только она готова, пока %s на максимуме, чтобы остановить перегрузку.", SCRIERS_GAZE, PERIL),
		ja = string.format("%sが最大のとき、%sが使用可能になった瞬間に自動で発動し、オーバーロードを止めます。", PERIL, SCRIERS_GAZE),
		ko = string.format("%s이 최대일 때 %s가 준비되는 즉시 자동으로 발동하여 과부하를 막습니다.", PERIL, SCRIERS_GAZE),
		["pt-br"] = string.format("Usa %s automaticamente assim que estiver pronta enquanto %s estiver no máximo, para deter a Sobrecarga.", SCRIERS_GAZE, PERIL),
		["zh-cn"] = string.format("当%s达到上限时，%s一就绪便自动发动以阻止过载。", PERIL, SCRIERS_GAZE),
		["zh-tw"] = string.format("當%s達到上限時，%s一就緒便自動發動以阻止超載。", PERIL, SCRIERS_GAZE),
	}),
	auto_use_shriek = {
		en = string.format("Auto-use %s", VENTING_SHRIEK),
		de = string.format("%s automatisch einsetzen", VENTING_SHRIEK),
		es = string.format("Usar %s automáticamente", VENTING_SHRIEK),
		fr = string.format("Utiliser %s automatiquement", VENTING_SHRIEK),
		it = string.format("Usa %s automaticamente", VENTING_SHRIEK),
		pl = string.format("Automatycznie używaj %s", VENTING_SHRIEK),
		ru = string.format("Автоприменение: %s", VENTING_SHRIEK),
		ja = string.format("%sを自動使用", VENTING_SHRIEK),
		ko = string.format("%s 자동 사용", VENTING_SHRIEK),
		["pt-br"] = string.format("Usar %s automaticamente", VENTING_SHRIEK),
		["zh-cn"] = string.format("自动使用%s", VENTING_SHRIEK),
		["zh-tw"] = string.format("自動使用%s", VENTING_SHRIEK),
	},
	auto_use_shriek_description = with_default(WORD_ON, {
		en = string.format("Automatically fire %s the moment it is ready while %s is at maximum, to stop the Overload.", VENTING_SHRIEK, PERIL),
		de = string.format("Setzt %s automatisch ein, sobald es bereit ist, während %s am Maximum ist, um die Überladung zu stoppen.", VENTING_SHRIEK, PERIL),
		es = string.format("Usa %s automáticamente en cuanto esté lista mientras %s está al máximo, para detener la Sobrecarga.", VENTING_SHRIEK, PERIL),
		fr = string.format("Utilise %s automatiquement dès qu'elle est prête tant que %s est au maximum, pour stopper la Surcharge.", VENTING_SHRIEK, PERIL),
		it = string.format("Usa %s automaticamente appena è pronta mentre %s è al massimo, per fermare il Sovraccarico.", VENTING_SHRIEK, PERIL),
		pl = string.format("Automatycznie używa %s, gdy tylko jest gotowe, gdy %s jest na maksimum, aby zatrzymać przeciążenie.", VENTING_SHRIEK, PERIL),
		ru = string.format("Автоматически применяет %s, как только она готова, пока %s на максимуме, чтобы остановить перегрузку.", VENTING_SHRIEK, PERIL),
		ja = string.format("%sが最大のとき、%sが使用可能になった瞬間に自動で発動し、オーバーロードを止めます。", PERIL, VENTING_SHRIEK),
		ko = string.format("%s이 최대일 때 %s가 준비되는 즉시 자동으로 발동하여 과부하를 막습니다.", PERIL, VENTING_SHRIEK),
		["pt-br"] = string.format("Usa %s automaticamente assim que estiver pronta enquanto %s estiver no máximo, para deter a Sobrecarga.", VENTING_SHRIEK, PERIL),
		["zh-cn"] = string.format("当%s达到上限时，%s一就绪便自动发动以阻止过载。", PERIL, VENTING_SHRIEK),
		["zh-tw"] = string.format("當%s達到上限時，%s一就緒便自動發動以阻止超載。", PERIL, VENTING_SHRIEK),
	}),
	auto_use_wrath = {
		en = string.format("Auto-use %s", PSYKINETICS_WRATH),
		de = string.format("%s automatisch einsetzen", PSYKINETICS_WRATH),
		es = string.format("Usar %s automáticamente", PSYKINETICS_WRATH),
		fr = string.format("Utiliser %s automatiquement", PSYKINETICS_WRATH),
		it = string.format("Usa %s automaticamente", PSYKINETICS_WRATH),
		pl = string.format("Automatycznie używaj %s", PSYKINETICS_WRATH),
		ru = string.format("Автоприменение: %s", PSYKINETICS_WRATH),
		ja = string.format("%sを自動使用", PSYKINETICS_WRATH),
		ko = string.format("%s 자동 사용", PSYKINETICS_WRATH),
		["pt-br"] = string.format("Usar %s automaticamente", PSYKINETICS_WRATH),
		["zh-cn"] = string.format("自动使用%s", PSYKINETICS_WRATH),
		["zh-tw"] = string.format("自動使用%s", PSYKINETICS_WRATH),
	},
	auto_use_wrath_description = with_default(WORD_ON, {
		en = string.format("Automatically fire %s the moment it is ready while %s is at maximum, to stop the Overload.", PSYKINETICS_WRATH, PERIL),
		de = string.format("Setzt %s automatisch ein, sobald es bereit ist, während %s am Maximum ist, um die Überladung zu stoppen.", PSYKINETICS_WRATH, PERIL),
		es = string.format("Usa %s automáticamente en cuanto esté lista mientras %s está al máximo, para detener la Sobrecarga.", PSYKINETICS_WRATH, PERIL),
		fr = string.format("Utilise %s automatiquement dès qu'elle est prête tant que %s est au maximum, pour stopper la Surcharge.", PSYKINETICS_WRATH, PERIL),
		it = string.format("Usa %s automaticamente appena è pronta mentre %s è al massimo, per fermare il Sovraccarico.", PSYKINETICS_WRATH, PERIL),
		pl = string.format("Automatycznie używa %s, gdy tylko jest gotowe, gdy %s jest na maksimum, aby zatrzymać przeciążenie.", PSYKINETICS_WRATH, PERIL),
		ru = string.format("Автоматически применяет %s, как только она готова, пока %s на максимуме, чтобы остановить перегрузку.", PSYKINETICS_WRATH, PERIL),
		ja = string.format("%sが最大のとき、%sが使用可能になった瞬間に自動で発動し、オーバーロードを止めます。", PERIL, PSYKINETICS_WRATH),
		ko = string.format("%s이 최대일 때 %s가 준비되는 즉시 자동으로 발동하여 과부하를 막습니다.", PERIL, PSYKINETICS_WRATH),
		["pt-br"] = string.format("Usa %s automaticamente assim que estiver pronta enquanto %s estiver no máximo, para deter a Sobrecarga.", PSYKINETICS_WRATH, PERIL),
		["zh-cn"] = string.format("当%s达到上限时，%s一就绪便自动发动以阻止过载。", PERIL, PSYKINETICS_WRATH),
		["zh-tw"] = string.format("當%s達到上限時，%s一就緒便自動發動以阻止超載。", PERIL, PSYKINETICS_WRATH),
	}),
	when_to_use = {
		en = "When to use",
		de = "Wann einsetzen",
		es = "Cuándo usar",
		fr = "Quand l'utiliser",
		it = "Quando usarla",
		pl = "Kiedy używać",
		ru = "Когда применять",
		ja = "使用タイミング",
		ko = "사용 시점",
		["pt-br"] = "Quando usar",
		["zh-cn"] = "使用时机",
		["zh-tw"] = "使用時機",
	},
	when_to_use_description = with_default(WORD_REACTIVE, {
		en = "Reactive (default) holds the ability for the instant an overload triggers. Proactive fires it as soon as it is off cooldown, waiting only for your current action to finish (e.g. it lets a flame staff cast end, then casts).",
		de = "Reaktiv (Standard) hält die Fähigkeit für den Moment zurück, in dem eine Überladung auslöst. Proaktiv setzt sie ein, sobald sie bereit ist, und wartet nur, bis deine aktuelle Aktion endet (z. B. lässt sie einen Flammenstab-Zauber auslaufen und setzt dann ein).",
		es = "Reactivo (predeterminado) reserva la habilidad para el instante en que se desencadena una sobrecarga. Proactivo la usa en cuanto sale del enfriamiento, esperando solo a que termine tu acción actual (p. ej., deja que acabe un lanzamiento del bastón de fuego y entonces la usa).",
		fr = "Réactif (par défaut) garde la capacité pour l'instant où une surcharge se déclenche. Proactif la déclenche dès qu'elle est disponible, en attendant seulement la fin de votre action en cours (p. ex. il laisse un tir de bâton de feu se terminer, puis l'utilise).",
		it = "Reattivo (predefinito) tiene l'abilità per l'istante in cui scatta un sovraccarico. Proattivo la usa appena è fuori ricarica, aspettando solo che finisca la tua azione attuale (es. lascia terminare un lancio del bastone di fuoco, poi la usa).",
		pl = "Reaktywny (domyślnie) trzyma zdolność na moment, w którym wyzwala się przeciążenie. Proaktywny używa jej, gdy tylko wyjdzie z odnowienia, czekając tylko na zakończenie bieżącej akcji (np. pozwala skończyć rzut ognistą laską, po czym jej używa).",
		ru = "Реактивно (по умолчанию) приберегает способность на момент, когда срабатывает перегрузка. Проактивно применяет её, как только она выйдет из отката, ожидая лишь завершения текущего действия (напр., даёт закончить каст огненного посоха, затем применяет).",
		ja = "リアクティブ（既定）はアビリティをオーバーロードが発生する瞬間まで温存します。プロアクティブはクールダウンが明けた瞬間に、現在のアクションが終わるのだけを待って発動します（例：フレイムスタッフのキャストが止まるのを待ってから発動）。",
		ko = "반응형(기본값)은 과부하가 발동하는 순간을 위해 능력을 아껴 둡니다. 선제형은 재사용 대기시간이 끝나는 즉시, 현재 행동이 끝나기만 기다렸다가 발동합니다(예: 화염 스태프 시전이 멈출 때까지 기다렸다가 발동).",
		["pt-br"] = "Reativo (padrão) guarda a habilidade para o instante em que uma sobrecarga dispara. Proativo a aciona assim que sai da recarga, esperando apenas sua ação atual terminar (ex.: deixa um lançamento do cajado de fogo acabar e então aciona).",
		["zh-cn"] = "响应式（默认）会把技能留到过载触发的瞬间。主动式则在技能冷却结束后立即施放，只等你当前的动作结束（例如等火焰法杖的施放停止后再施放）。",
		["zh-tw"] = "回應式（預設）會把技能留到超載觸發的瞬間。主動式則在技能冷卻結束後立即施放，只等你當前的動作結束（例如等火焰法杖的施放停止後再施放）。",
	}),
	min_peril = {
		en = string.format("Minimum %s threshold", PERIL),
		de = string.format("Mindest-%s-Schwelle", PERIL),
		es = string.format("Umbral mínimo de %s", PERIL),
		fr = string.format("Seuil minimum de %s", PERIL),
		it = string.format("Soglia minima di %s", PERIL),
		pl = string.format("Minimalny próg %s", PERIL),
		ru = string.format("Минимальный порог %s", PERIL),
		ja = string.format("%sの最小しきい値", PERIL),
		ko = string.format("최소 %s 임계값", PERIL),
		["pt-br"] = string.format("Limite mínimo de %s", PERIL),
		["zh-cn"] = string.format("最低%s阈值", PERIL),
		["zh-tw"] = string.format("最低%s閾值", PERIL),
	},
	min_peril_description = with_default("0", {
		en = string.format("In Proactive mode, only fire the ability once %s is at least this percentage (0-100). 0 fires regardless. Reactive is unaffected.", PERIL),
		de = string.format("Im Proaktiv-Modus wird die Fähigkeit erst eingesetzt, wenn %s mindestens diesen Prozentsatz erreicht (0-100). 0 setzt sie immer ein. Reaktiv bleibt unberührt.", PERIL),
		es = string.format("En modo Proactivo, solo usa la habilidad cuando %s alcanza al menos este porcentaje (0-100). 0 la usa siempre. Reactivo no se ve afectado.", PERIL),
		fr = string.format("En mode Proactif, la capacité ne se déclenche que lorsque le %s atteint au moins ce pourcentage (0-100). 0 la déclenche toujours. Le mode Réactif n'est pas affecté.", PERIL),
		it = string.format("In modalità Proattiva, l'abilità si attiva solo quando il %s raggiunge almeno questa percentuale (0-100). 0 la attiva sempre. La modalità Reattiva non è influenzata.", PERIL),
		pl = string.format("W trybie Proaktywnym zdolność uruchamia się dopiero, gdy %s osiągnie co najmniej ten procent (0-100). 0 uruchamia zawsze. Tryb Reaktywny pozostaje bez zmian.", PERIL),
		ru = string.format("В Проактивном режиме способность применяется, только когда %s достигает хотя бы этого процента (0-100). 0 — применять всегда. На Реактивный режим не влияет.", PERIL),
		ja = string.format("プロアクティブでは、%sがこの割合（0～100）以上のときだけアビリティを発動します。0なら常に発動。リアクティブには影響しません。", PERIL),
		ko = string.format("선제형에서는 %s이 이 비율(0-100) 이상일 때만 능력을 발동합니다. 0이면 항상 발동합니다. 반응형에는 영향을 주지 않습니다.", PERIL),
		["pt-br"] = string.format("No modo Proativo, a habilidade só é acionada quando o %s atinge pelo menos esta porcentagem (0-100). 0 aciona sempre. O modo Reativo não é afetado.", PERIL),
		["zh-cn"] = string.format("主动式下，仅当%s达到至少该百分比（0-100）时才发动技能。0表示始终发动。不影响响应式。", PERIL),
		["zh-tw"] = string.format("主動式下，僅當%s達到至少該百分比（0-100）時才發動技能。0表示始終發動。不影響回應式。", PERIL),
	}),
	recover_window = {
		en = "Cooldown tolerance (seconds)",
		de = "Abklingzeit-Toleranz (Sekunden)",
		es = "Tolerancia de enfriamiento (segundos)",
		fr = "Tolérance de recharge (secondes)",
		it = "Tolleranza di ricarica (secondi)",
		pl = "Tolerancja odnowienia (sekundy)",
		ru = "Допуск перезарядки (секунды)",
		ja = "クールダウン許容値（秒）",
		ko = "재사용 대기시간 허용치 (초)",
		["pt-br"] = "Tolerância de recarga (segundos)",
		["zh-cn"] = "冷却容差（秒）",
		["zh-tw"] = "冷卻容差（秒）",
	},
	recover_window_description = with_default("0.0", {
		en = string.format("Still count as SAFE while %s, %s or %s is this close to ready - regardless of choice, you can still stop the overload in time.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		de = string.format("Gilt weiterhin als SICHER, solange %s, %s oder %s so kurz vor der Bereitschaft steht - unabhängig von der Wahl stoppst du die Überladung noch rechtzeitig.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		es = string.format("Sigues contando como SEGURO mientras a %s, %s o %s le falte este tiempo para estar listo - sea cual sea tu elección, aún puedes detener la sobrecarga a tiempo.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		fr = string.format("Reste considéré comme SÛR tant que %s, %s ou %s est à ce délai d'être prêt - quel que soit votre choix, vous pouvez encore stopper la surcharge à temps.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		it = string.format("Conta ancora come SICURO finché a %s, %s o %s manca questo tempo per essere pronto - a prescindere dalla scelta, puoi ancora fermare il sovraccarico in tempo.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		pl = string.format("Nadal liczy się jako BEZPIECZNIE, dopóki %s, %s lub %s jest tak blisko gotowości - niezależnie od wyboru wciąż zdążysz zatrzymać przeciążenie.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ru = string.format("Всё ещё считается БЕЗОПАСНО, пока %s, %s или %s осталось столько до готовности - независимо от выбора вы успеете остановить перегрузку.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ja = string.format("%s、%sまたは%sの再使用までこの秒数以内なら安全と見なします。どれを選んでいてもオーバーロードを間に合って止められます。", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ko = string.format("%s, %s 또는 %s이 이만큼 안에 준비되면 계속 안전으로 간주합니다. 어느 것을 선택했든 제때 과부하를 멈출 수 있습니다.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["pt-br"] = string.format("Ainda conta como SEGURO enquanto %s, %s ou %s estiver a este tempo de ficar pronto - independentemente da escolha, você ainda interrompe a sobrecarga a tempo.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["zh-cn"] = string.format("只要%s、%s或%s距离就绪不超过这么久，就仍视为安全。无论选择哪个，你都能及时中止过载。", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["zh-tw"] = string.format("只要%s、%s或%s距離就緒不超過這麼久，就仍視為安全。無論選擇哪個，你都能及時中止超載。", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
	}),
	auto_fire_before_unsafe = {
		en = "Auto fire before unsafe",
		de = "Auto-Feuer vor UNSICHER",
		es = "Disparo auto. antes de PELIGRO",
		fr = "Tir auto. avant DANGER",
		it = "Fuoco auto. prima di PERICOLO",
		pl = "Auto-strzał przed NIEBEZPIECZNIE",
		ru = "Автовыстрел до ОПАСНО",
		ja = "危険前に自動発射",
		ko = "위험 전 자동 발사",
		["pt-br"] = "Disparo auto. antes de PERIGO",
		["zh-cn"] = "危险前自动发射",
		["zh-tw"] = "危險前自動發射",
	},
	auto_fire_before_unsafe_description = with_default(WORD_ON, {
		en = string.format("Automatically fires a charging staff just before %s reaches UNSAFE to prevent overloading.", PERIL),
		de = string.format("Feuert automatisch einen aufladenden Stab ab, kurz bevor %s UNSICHER erreicht, um eine Überladung zu verhindern.", PERIL),
		es = string.format("Dispara automáticamente un bastón en carga justo antes de que %s alcance PELIGRO para evitar la Sobrecarga.", PERIL),
		fr = string.format("Tire automatiquement un bâton en charge juste avant que %s n'atteigne DANGER pour éviter la Surcharge.", PERIL),
		it = string.format("Spara automaticamente un bastone in carica poco prima che %s raggiunga PERICOLO per evitare il Sovraccarico.", PERIL),
		pl = string.format("Automatycznie strzela z ładowanej laski tuż przed osiągnięciem przez %s poziomu NIEBEZPIECZNIE, aby zapobiec przeciążeniu.", PERIL),
		ru = string.format("Автоматически стреляет из заряжаемого посоха прямо перед тем, как %s достигнет ОПАСНО, чтобы предотвратить перегрузку.", PERIL),
		ja = string.format("%sが危険に達する直前にチャージ中のスタッフを自動で発射し、オーバーロードを防ぎます。", PERIL),
		ko = string.format("%s이 위험에 도달하기 직전에 충전 중인 스태프를 자동으로 발사하여 과부하를 방지합니다.", PERIL),
		["pt-br"] = string.format("Dispara automaticamente um cajado em carga pouco antes de %s atingir PERIGO para evitar a Sobrecarga.", PERIL),
		["zh-cn"] = string.format("在%s达到危险之前自动发射充能中的法杖，以防止过载。", PERIL),
		["zh-tw"] = string.format("在%s達到危險之前自動發射充能中的法杖，以防止超載。", PERIL),
	}),
	auto_quell = {
		en = "Automatic quelling",
		de = "Automatisches Entladen",
		es = "Sofocado automático",
		fr = "Apaisement automatique",
		it = "Sfogo automatico",
		pl = "Automatyczne wygaszanie",
		ru = "Автоматическое усмирение",
		ja = "自動クエル",
		ko = "자동 진정",
		["pt-br"] = "Dissipação automática",
		["zh-cn"] = "自动平息",
		["zh-tw"] = "自動平息",
	},
	auto_quell_description = with_default(WORD_ON, {
		en = string.format("Holds %s to quell %s while UNSAFE, or from the start value below. Never during %s.", RELOAD, PERIL, WARP_UNBOUND),
		de = string.format("Hält bei UNSICHER oder ab dem Startwert unten %s gedrückt, um %s zu entladen. Nie während %s.", RELOAD, PERIL, WARP_UNBOUND),
		es = string.format("Mantiene %s pulsado para sofocar %s mientras estés en PELIGRO, o desde el valor de inicio de abajo. Nunca durante %s.", RELOAD, PERIL, WARP_UNBOUND),
		fr = string.format("Maintient %s pour apaiser le %s en état de DANGER, ou dès la valeur de départ ci-dessous. Jamais pendant %s.", RELOAD, PERIL, WARP_UNBOUND),
		it = string.format("Tiene premuto %s per sfogare il %s quando sei in PERICOLO, o dal valore di partenza qui sotto. Mai durante %s.", RELOAD, PERIL, WARP_UNBOUND),
		pl = string.format("Przytrzymuje %s, aby wygasić %s w stanie NIEBEZPIECZNIE lub od wartości startowej poniżej. Nigdy podczas %s.", RELOAD, PERIL, WARP_UNBOUND),
		ru = string.format("Удерживает %s, чтобы усмирить %s в состоянии ОПАСНО или начиная с порога ниже. Никогда во время %s.", RELOAD, PERIL, WARP_UNBOUND),
		ja = string.format("危険の間（または下の開始値から）、%sを押し続けて%sをクエルします。%s中は作動しません。", RELOAD, PERIL, WARP_UNBOUND),
		ko = string.format("위험 상태일 때(또는 아래 시작 수치부터) %s를 눌러 %s를 진정시킵니다. %s 중에는 작동하지 않습니다.", RELOAD, PERIL, WARP_UNBOUND),
		["pt-br"] = string.format("Segura %s para dissipar %s enquanto estiver em PERIGO, ou a partir do valor inicial abaixo. Nunca durante %s.", RELOAD, PERIL, WARP_UNBOUND),
		["zh-cn"] = string.format("处于危险时（或从下方的起始值起）按住%s平息%s。%s期间不触发。", RELOAD, PERIL, WARP_UNBOUND),
		["zh-tw"] = string.format("處於危險時（或從下方的起始值起）按住%s平息%s。%s期間不觸發。", RELOAD, PERIL, WARP_UNBOUND),
	}),
	auto_quell_scriers = {
		en = string.format("Quell during %s", SCRIERS_GAZE),
		de = string.format("Während %s entladen", SCRIERS_GAZE),
		es = string.format("Sofocar durante %s", SCRIERS_GAZE),
		fr = string.format("Apaiser pendant %s", SCRIERS_GAZE),
		it = string.format("Sfoga durante %s", SCRIERS_GAZE),
		pl = string.format("Wygaszaj podczas %s", SCRIERS_GAZE),
		ru = string.format("Усмирять во время %s", SCRIERS_GAZE),
		ja = string.format("%s中にクエル", SCRIERS_GAZE),
		ko = string.format("%s 중 진정", SCRIERS_GAZE),
		["pt-br"] = string.format("Dissipar durante %s", SCRIERS_GAZE),
		["zh-cn"] = string.format("%s期间平息", SCRIERS_GAZE),
		["zh-tw"] = string.format("%s期間平息", SCRIERS_GAZE),
	},
	auto_quell_scriers_description = with_default(WORD_OFF, {
		en = string.format("Also quell while %s is active, to keep the stance and its stack gains going: it ends the instant %s reaches 100 percent. Quelling starts at the latest safe moment, worked out live from the stance's own climb, your current attack and the quell's start-up time, or at your start value if that is lower. With offensive interrupts off, it also holds back a staff shot that would end the stance and cuts a Purgatus stream short when needed.", SCRIERS_GAZE, PERIL),
		de = string.format("Entlädt auch während %s, damit die Haltung und ihr Stapelaufbau weiterlaufen: Sie endet, sobald %s 100 Prozent erreicht. Das Entladen beginnt im spätesten sicheren Moment, laufend berechnet aus dem Anstieg der Haltung, deinem aktuellen Angriff und der Anlaufzeit des Entladens, oder bei deinem Startwert, falls dieser niedriger ist. Bei ausgeschalteten Angriffsunterbrechungen hält es außerdem einen Stabschuss zurück, der die Haltung beenden würde, und bricht einen Purgatus-Strahl bei Bedarf ab.", SCRIERS_GAZE, PERIL),
		es = string.format("También sofoca mientras %s está activa, para mantener la postura y sus acumulaciones: termina en cuanto %s llega al 100 por ciento. El sofocado empieza en el último momento seguro, calculado en vivo a partir del aumento propio de la postura, tu ataque actual y el tiempo de arranque del sofocado, o en tu valor de inicio si es menor. Con las interrupciones ofensivas desactivadas, también retiene un disparo de bastón que acabaría con la postura y corta un chorro de Purgatus cuando hace falta.", SCRIERS_GAZE, PERIL),
		fr = string.format("Apaise aussi pendant %s pour maintenir la posture et ses cumuls : elle prend fin dès que le %s atteint 100 pour cent. L'apaisement commence au dernier moment sûr, calculé en direct d'après la hausse propre à la posture, votre attaque en cours et le délai de démarrage de l'apaisement, ou à votre valeur de départ si elle est plus basse. Avec les interruptions offensives désactivées, il retient aussi un tir de bâton qui mettrait fin à la posture et écourte un flux de Purgatus si nécessaire.", SCRIERS_GAZE, PERIL),
		it = string.format("Sfoga anche mentre %s è attivo, per mantenere la postura e l'accumulo di cariche: termina appena il %s raggiunge il 100 per cento. Lo sfogo inizia all'ultimo momento sicuro, calcolato in tempo reale dall'aumento proprio della postura, dal tuo attacco in corso e dal tempo di avvio dello sfogo, oppure al tuo valore di partenza se è più basso. Con le interruzioni offensive disattivate, trattiene anche un colpo di bastone che farebbe terminare la postura e interrompe un getto di Purgatus quando serve.", SCRIERS_GAZE, PERIL),
		pl = string.format("Wygasza także podczas %s, aby podtrzymać postawę i przyrost ładunków: kończy się, gdy %s osiągnie 100 procent. Wygaszanie zaczyna się w ostatnim bezpiecznym momencie, liczonym na bieżąco z przyrostu samej postawy, twojego bieżącego ataku i czasu rozruchu wygaszania, albo od twojej wartości startowej, jeśli jest niższa. Przy wyłączonym przerywaniu akcjami ofensywnymi wstrzymuje też strzał z kostura, który zakończyłby postawę, i w razie potrzeby przerywa strumień laski psionicznej oczyszczenia.", SCRIERS_GAZE, PERIL),
		ru = string.format("Усмиряет и во время %s, чтобы стойка и набор зарядов продолжались: она заканчивается, как только %s достигает 100 процентов. Усмирение начинается в последний безопасный момент, который рассчитывается на лету по росту от самой стойки, вашей текущей атаке и времени запуска усмирения, или с вашего порога, если он ниже. При выключенном прерывании атакующими действиями также сдерживает выстрел посоха, который завершил бы стойку, и при необходимости обрывает поток психосилового посоха чистки.", SCRIERS_GAZE, PERIL),
		ja = string.format("%s中もクエルし、スタンスとスタック獲得を維持します。%sが100パーセントに達した瞬間にスタンスは終了します。クエルは、スタンス自体の上昇量、現在の攻撃、クエルの立ち上がり時間からリアルタイムで算出した最も遅い安全なタイミング、または開始値のうち低い方で始まります。攻撃行動による中断がオフの場合、スタンスを終わらせてしまう杖の射撃を止め、必要ならプルガタスの放射を途中で打ち切ります。", SCRIERS_GAZE, PERIL),
		ko = string.format("%s 중에도 진정하여 자세와 중첩 획득을 유지합니다. %s가 100퍼센트에 도달하는 순간 자세가 끝납니다. 진정은 자세 자체의 상승량, 현재 공격, 진정 시작 시간으로 실시간 계산한 가장 늦은 안전 시점, 또는 시작 수치 중 낮은 쪽에서 시작합니다. 공격 행동 중단이 꺼져 있으면, 자세를 끝낼 지팡이 사격을 막고 필요하면 푸르가투스 방사를 도중에 끊습니다.", SCRIERS_GAZE, PERIL),
		["pt-br"] = string.format("Também dissipa enquanto %s está ativo, para manter a postura e o ganho de acúmulos: ela termina assim que %s chega a 100 por cento. A dissipação começa no último momento seguro, calculado em tempo real a partir do aumento da própria postura, do seu ataque atual e do tempo de início da dissipação, ou no seu valor inicial se for menor. Com as interrupções ofensivas desligadas, também segura um disparo de cajado que encerraria a postura e corta um fluxo do Purgatus quando necessário.", SCRIERS_GAZE, PERIL),
		["zh-cn"] = string.format("在%s期间也进行平息，以维持姿态及其层数增长：%s达到百分之百时姿态立即结束。平息会在最晚的安全时机开始（根据姿态自身的上涨、你当前的攻击和平息的启动时间实时计算），若你的起始值更低则按起始值开始。关闭进攻动作中断时，还会拦下会结束姿态的法杖射击，并在需要时截断净化力场杖的喷流。", SCRIERS_GAZE, PERIL),
		["zh-tw"] = string.format("在%s期間也進行平息，以維持姿態及其層數增長：%s達到百分之百時姿態立即結束。平息會在最晚的安全時機開始（根據姿態自身的上漲、你目前的攻擊和平息的啟動時間即時計算），若你的起始值更低則按起始值開始。關閉進攻動作中斷時，還會攔下會結束姿態的法杖射擊，並在需要時截斷淨化力場法杖的噴流。", SCRIERS_GAZE, PERIL),
	}),
	auto_quell_scriers_stacks = {
		en = "Quell until Precognition stacks",
		de = "Entladen bis Vorausahnung-Stapel",
		es = "Sofocar hasta acumulaciones de Precognición",
		fr = "Apaiser jusqu'à cumuls de Précognition",
		it = "Sfoga fino a cariche di Precognizione",
		pl = "Wygaszaj do ładunków Prekognicji",
		ru = "Усмирять до зарядов Познания",
		ja = "予知スタック数までクエル",
		ko = "예지 중첩까지 진정",
		["pt-br"] = "Dissipar até acúmulos de Profecia",
		["zh-cn"] = "平息至预知层数",
		["zh-tw"] = "平息至預知未來層數",
	},
	auto_quell_scriers_stacks_description = with_default("30", {
		en = string.format("Quell during %s only until the stance has this many Precognition stacks, then let it run out. Keeping it up late costs more quelling than attacking time. 0 = never, 30 = up to the cap.", SCRIERS_GAZE),
		de = string.format("Entlädt während %s nur, bis die Haltung so viele Vorausahnung-Stapel hat, und lässt sie danach auslaufen. Sie spät zu halten kostet mehr Entladezeit als Angriffszeit. 0 = nie, 30 = bis zum Maximum.", SCRIERS_GAZE),
		es = string.format("Sofoca durante %s solo hasta que la postura tenga estas acumulaciones de Precognición y luego deja que se agote. Mantenerla hasta tarde cuesta más tiempo sofocando que atacando. 0 = nunca, 30 = hasta el máximo.", SCRIERS_GAZE),
		fr = string.format("N'apaise pendant %s que jusqu'à ce que la posture ait ce nombre de cumuls de Précognition, puis la laisse s'épuiser. La maintenir tard coûte plus de temps d'apaisement que d'attaque. 0 = jamais, 30 = jusqu'au maximum.", SCRIERS_GAZE),
		it = string.format("Sfoga durante %s solo finché la postura non ha queste cariche di Precognizione, poi la lascia esaurire. Tenerla a lungo costa più tempo di sfogo che di attacco. 0 = mai, 30 = fino al massimo.", SCRIERS_GAZE),
		pl = string.format("Wygasza podczas %s tylko do chwili, gdy postawa ma tyle ładunków Prekognicji, potem pozwala jej wygasnąć. Utrzymywanie jej długo kosztuje więcej czasu wygaszania niż ataku. 0 = nigdy, 30 = do maksimum.", SCRIERS_GAZE),
		ru = string.format("Усмиряет во время %s только пока у стойки не наберётся столько зарядов Познания, затем даёт ей закончиться. Долгое удержание отнимает больше времени на усмирение, чем на атаку. 0 = никогда, 30 = до максимума.", SCRIERS_GAZE),
		ja = string.format("%s中は、予知スタックがこの数になるまでだけクエルし、その後はスタンスを自然に終わらせます。長く維持するほど攻撃よりクエルの時間が増えます。0 = しない、30 = 上限まで。", SCRIERS_GAZE),
		ko = string.format("%s 중에는 예지 중첩이 이 수에 도달할 때까지만 진정하고, 그 뒤에는 자세가 끝나도록 둡니다. 오래 유지할수록 공격보다 진정에 더 많은 시간이 듭니다. 0 = 안 함, 30 = 최대치까지.", SCRIERS_GAZE),
		["pt-br"] = string.format("Dissipa durante %s só até a postura ter esta quantidade de acúmulos de Profecia, depois deixa que ela acabe. Mantê-la por muito tempo custa mais tempo dissipando do que atacando. 0 = nunca, 30 = até o máximo.", SCRIERS_GAZE),
		["zh-cn"] = string.format("在%s期间只平息到姿态拥有这么多预知层数，之后让它自然结束。维持越久，平息占用的时间比攻击还多。0 = 从不，30 = 直到上限。", SCRIERS_GAZE),
		["zh-tw"] = string.format("在%s期間只平息到姿態擁有這麼多預知未來層數，之後讓它自然結束。維持越久，平息佔用的時間比攻擊還多。0 = 從不，30 = 直到上限。", SCRIERS_GAZE),
	}),
	-- No literal "%" in displayed text: DMF runs it through string.format.
	auto_quell_trigger = {
		en = string.format("Start quelling at %s (percent)", PERIL),
		de = string.format("Entladen ab %s (Prozent)", PERIL),
		es = string.format("Sofocar desde %s (porcentaje)", PERIL),
		fr = string.format("Apaiser à partir de %s (pourcentage)", PERIL),
		it = string.format("Sfogo a partire da %s (percentuale)", PERIL),
		pl = string.format("Wygaszaj od %s (procent)", PERIL),
		ru = string.format("Усмирять от %s (процент)", PERIL),
		ja = string.format("%sのクエル開始値（パーセント）", PERIL),
		ko = string.format("%s 진정 시작 수치 (퍼센트)", PERIL),
		["pt-br"] = string.format("Dissipar a partir de %s (porcentagem)", PERIL),
		["zh-cn"] = string.format("%s平息触发值（百分比）", PERIL),
		["zh-tw"] = string.format("%s平息觸發值（百分比）", PERIL),
	},
	auto_quell_trigger_description = with_default("100.0", {
		en = string.format("Start quelling once %s reaches this percentage, instead of only at the overload limit. 100 = only at the limit. The interrupt settings below still apply.", PERIL),
		de = string.format("Beginnt das Entladen, sobald %s diesen Prozentwert erreicht, statt erst am Überladungslimit. 100 = nur am Limit. Die Unterbrechungseinstellungen unten gelten weiterhin.", PERIL),
		es = string.format("Empieza a sofocar cuando %s alcanza este porcentaje, en vez de solo al límite de sobrecarga. 100 = solo al límite. Los ajustes de interrupción de abajo siguen aplicándose.", PERIL),
		fr = string.format("Commence à apaiser dès que le %s atteint ce pourcentage, au lieu d'attendre la limite de surcharge. 100 = seulement à la limite. Les réglages d'interruption ci-dessous s'appliquent toujours.", PERIL),
		it = string.format("Inizia a sfogare quando il %s raggiunge questa percentuale, invece che solo al limite di sovraccarico. 100 = solo al limite. Le impostazioni di interruzione qui sotto restano valide.", PERIL),
		pl = string.format("Zaczyna wygaszanie, gdy %s osiągnie ten procent, zamiast dopiero na granicy przeciążenia. 100 = tylko na granicy. Ustawienia przerywania poniżej nadal obowiązują.", PERIL),
		ru = string.format("Начинает усмирение, когда %s достигает этого процента, а не только на пределе перегрузки. 100 = только на пределе. Настройки прерывания ниже по-прежнему действуют.", PERIL),
		ja = string.format("%sがこの割合に達したらクエルを開始します（過負荷の限界まで待ちません）。100 = 限界時のみ。下の中断設定は引き続き適用されます。", PERIL),
		ko = string.format("%s가 이 비율에 도달하면 과부하 한계까지 기다리지 않고 진정을 시작합니다. 100 = 한계에서만. 아래 중단 설정은 계속 적용됩니다.", PERIL),
		["pt-br"] = string.format("Começa a dissipar quando %s atinge esta porcentagem, em vez de só no limite de sobrecarga. 100 = só no limite. As configurações de interrupção abaixo continuam valendo.", PERIL),
		["zh-cn"] = string.format("当%s达到该百分比时即开始平息，而不是等到过载临界点。100 = 仅在临界点。下方的中断设置仍然适用。", PERIL),
		["zh-tw"] = string.format("當%s達到該百分比時即開始平息，而不是等到過載臨界點。100 = 僅在臨界點。下方的中斷設定仍然適用。", PERIL),
	}),
	auto_quell_interrupt_offensive = {
		en = "Interrupt Quelling on Offensive Actions",
		de = "Entladen bei Angriffsaktionen unterbrechen",
		es = "Interrumpir sofocado con acciones ofensivas",
		fr = "Interrompre l'apaisement sur action offensive",
		it = "Interrompi lo sfogo con azioni offensive",
		pl = "Przerywaj wygaszanie akcjami ofensywnymi",
		ru = "Прерывать усмирение атакующими действиями",
		ja = "攻撃行動でクエルを中断",
		ko = "공격 행동 시 진정 중단",
		["pt-br"] = "Interromper dissipação com ações ofensivas",
		["zh-cn"] = "进攻动作中断平息",
		["zh-tw"] = "進攻動作中斷平息",
	},
	auto_quell_interrupt_offensive_description = with_default(WORD_OFF, {
		en = string.format("Off: while quelling, new attacks, charges, weapon specials and %s are blocked, so the quell runs its course (an attack already under way still finishes). On: any of them pauses quelling for as long as you keep doing it.", BLITZ),
		de = string.format("Aus: Während des Entladens werden neue Angriffe, Aufladungen, Waffenspezialaktionen und %s blockiert, damit das Entladen durchläuft (ein bereits laufender Angriff wird noch beendet). An: Jede dieser Aktionen pausiert das Entladen, solange du sie ausführst.", BLITZ),
		es = string.format("Desactivado: mientras sofocas se bloquean nuevos ataques, cargas, acciones especiales del arma y %s, para que el sofocado termine (un ataque ya en curso sí se completa). Activado: cualquiera de ellos pausa el sofocado mientras lo sigas haciendo.", BLITZ),
		fr = string.format("Désactivé : pendant l'apaisement, les nouvelles attaques, charges, actions spéciales d'arme et %s sont bloquées pour que l'apaisement aille à son terme (une attaque déjà en cours se termine). Activé : chacune met l'apaisement en pause tant que vous la poursuivez.", BLITZ),
		it = string.format("Disattivo: durante lo sfogo nuovi attacchi, cariche, azioni speciali dell'arma e %s sono bloccati, così lo sfogo arriva in fondo (un attacco già in corso termina comunque). Attivo: ognuno di essi mette in pausa lo sfogo finché continui a farlo.", BLITZ),
		pl = string.format("Wył.: podczas wygaszania nowe ataki, ładowania, akcje specjalne broni i %s są blokowane, aby wygaszanie dobiegło końca (atak już w toku zostanie dokończony). Wł.: każda z nich wstrzymuje wygaszanie, dopóki ją wykonujesz.", BLITZ),
		ru = string.format("Выкл.: во время усмирения новые атаки, заряды, особые действия оружия и %s блокируются, чтобы усмирение завершилось (уже начатая атака доводится до конца). Вкл.: любое из них приостанавливает усмирение, пока вы его выполняете.", BLITZ),
		ja = string.format("オフ：クエル中は新たな攻撃、チャージ、武器の特殊アクション、%sをブロックし、クエルを最後まで行います（すでに始まっている攻撃は最後まで実行されます）。オン：それらを行っている間、クエルを一時停止します。", BLITZ),
		ko = string.format("꺼짐: 진정 중에는 새로운 공격, 충전, 무기 특수 행동, %s을(를) 막아 진정을 끝까지 진행합니다(이미 진행 중인 공격은 끝까지 수행됩니다). 켜짐: 이러한 행동을 하는 동안 진정을 일시 정지합니다.", BLITZ),
		["pt-br"] = string.format("Desligado: durante a dissipação, novos ataques, cargas, ações especiais da arma e %s são bloqueados para que a dissipação termine (um ataque já em andamento ainda é concluído). Ligado: qualquer um deles pausa a dissipação enquanto você o fizer.", BLITZ),
		["zh-cn"] = string.format("关闭：平息期间会阻止新的攻击、蓄力、武器特殊动作和%s，让平息完整进行（已在进行中的攻击仍会完成）。开启：进行其中任何动作时，平息会暂停，直到你停止。", BLITZ),
		["zh-tw"] = string.format("關閉：平息期間會阻止新的攻擊、蓄力、武器特殊動作和%s，讓平息完整進行（已在進行中的攻擊仍會完成）。開啟：進行其中任何動作時，平息會暫停，直到你停止。", BLITZ),
	}),
	auto_quell_interrupt_other = {
		en = "Interrupt Quelling on Other Actions",
		de = "Entladen bei anderen Aktionen unterbrechen",
		es = "Interrumpir sofocado con otras acciones",
		fr = "Interrompre l'apaisement sur autre action",
		it = "Interrompi lo sfogo con altre azioni",
		pl = "Przerywaj wygaszanie innymi akcjami",
		ru = "Прерывать усмирение другими действиями",
		ja = "その他の行動でクエルを中断",
		ko = "기타 행동 시 진정 중단",
		["pt-br"] = "Interromper dissipação com outras ações",
		["zh-cn"] = "其他动作中断平息",
		["zh-tw"] = "其他動作中斷平息",
	},
	auto_quell_interrupt_other_description = with_default(WORD_ON, {
		en = "On: blocking, pushing or sprinting pauses quelling for as long as you keep doing it. Off: quelling overrides them and releases a held block. Dodging, jumping, abilities and weapon swaps always work alongside quelling.",
		de = "An: Blocken, Zurückstoßen oder Sprinten pausiert das Entladen, solange du es tust. Aus: Das Entladen hat Vorrang und löst einen gehaltenen Block. Ausweichen, Springen, Fähigkeiten und Waffenwechsel funktionieren während des Entladens immer.",
		es = "Activado: bloquear, empujar o esprintar pausa el sofocado mientras lo sigas haciendo. Desactivado: el sofocado tiene prioridad y suelta un bloqueo mantenido. Esquivar, saltar, las habilidades y cambiar de arma siempre funcionan mientras sofocas.",
		fr = "Activé : bloquer, pousser ou sprinter met l'apaisement en pause tant que vous le faites. Désactivé : l'apaisement a la priorité et relâche un blocage maintenu. Esquiver, sauter, les capacités et le changement d'arme fonctionnent toujours pendant l'apaisement.",
		it = "Attivo: parare, spingere o scattare mette in pausa lo sfogo finché continui a farlo. Disattivo: lo sfogo ha la precedenza e rilascia una parata tenuta. Schivare, saltare, le abilità e il cambio d'arma funzionano sempre durante lo sfogo.",
		pl = "Wł.: blokowanie, odepchnięcie lub sprint wstrzymuje wygaszanie, dopóki to robisz. Wył.: wygaszanie ma pierwszeństwo i zwalnia przytrzymany blok. Uniki, skoki, zdolności i zmiana broni zawsze działają podczas wygaszania.",
		ru = "Вкл.: блок, толчок или бег приостанавливают усмирение, пока вы их выполняете. Выкл.: усмирение важнее и отпускает удерживаемый блок. Уклонение, прыжки, способности и смена оружия всегда работают во время усмирения.",
		ja = "オン：ブロック、押し、ダッシュをしている間、クエルを一時停止します。オフ：クエルを優先し、押しているブロックを解除します。回避、ジャンプ、アビリティ、武器切り替えはクエル中も常に使えます。",
		ko = "켜짐: 막기, 밀기, 질주를 하는 동안 진정을 일시 정지합니다. 꺼짐: 진정이 우선하며 누르고 있는 막기를 해제합니다. 회피, 점프, 능력, 무기 교체는 진정 중에도 항상 사용할 수 있습니다.",
		["pt-br"] = "Ligado: bloquear, empurrar ou correr pausa a dissipação enquanto você o fizer. Desligado: a dissipação tem prioridade e solta um bloqueio mantido. Esquivar, pular, habilidades e trocar de arma sempre funcionam durante a dissipação.",
		["zh-cn"] = "开启：格挡、推击或冲刺时，平息会暂停，直到你停止。关闭：平息优先，并会松开正在按住的格挡。闪避、跳跃、技能和切换武器在平息期间始终可用。",
		["zh-tw"] = "開啟：格擋、推搡或衝刺時，平息會暫停，直到你停止。關閉：平息優先，並會鬆開正在按住的格擋。閃避、跳躍、技能和切換武器在平息期間始終可用。",
	}),
	auto_quell_hold = {
		en = "Extra quell hold (seconds)",
		de = "Zusätzliches Entladen (Sekunden)",
		es = "Sofocado adicional (segundos)",
		fr = "Apaisement supplémentaire (secondes)",
		it = "Sfogo aggiuntivo (secondi)",
		pl = "Dodatkowe wygaszanie (sekundy)",
		ru = "Доп. усмирение (секунды)",
		ja = "追加クエル時間（秒）",
		ko = "추가 진정 시간 (초)",
		["pt-br"] = "Dissipação extra (segundos)",
		["zh-cn"] = "额外平息时长（秒）",
		["zh-tw"] = "額外平息時長（秒）",
	},
	auto_quell_hold_description = with_default("0.3", {
		en = string.format("Keep quelling this long after UNSAFE (or the %s quell point) clears, instead of stopping at the edge. 0 = stop immediately.", SCRIERS_GAZE),
		de = string.format("Entlädt nach dem Ende von UNSICHER (oder des %s-Entladepunkts) noch so lange weiter, statt am Limit zu stoppen. 0 = sofort stoppen.", SCRIERS_GAZE),
		es = string.format("Sigue sofocando este tiempo después de dejar de estar en PELIGRO (o de bajar del punto de sofocado de %s), en vez de parar al borde. 0 = parar de inmediato.", SCRIERS_GAZE),
		fr = string.format("Continue d'apaiser pendant ce délai après la fin du DANGER (ou du point d'apaisement de %s), au lieu de s'arrêter à la limite. 0 = arrêt immédiat.", SCRIERS_GAZE),
		it = string.format("Continua a sfogare per questo tempo dopo la fine del PERICOLO (o del punto di sfogo di %s), invece di fermarsi al limite. 0 = ferma subito.", SCRIERS_GAZE),
		pl = string.format("Wygasza jeszcze tak długo po ustaniu stanu NIEBEZPIECZNIE (lub punktu wygaszania %s), zamiast zatrzymywać się na krawędzi. 0 = zatrzymaj natychmiast.", SCRIERS_GAZE),
		ru = string.format("Продолжает усмирение столько после снятия ОПАСНО (или точки усмирения %s), вместо остановки на грани. 0 = остановиться сразу.", SCRIERS_GAZE),
		ja = string.format("危険（または%sのクエル開始点）が解除された後もこの秒数だけクエルを続けます（限界ぎりぎりで止めない）。0 = 即座に停止。", SCRIERS_GAZE),
		ko = string.format("위험(또는 %s 진정 시점)이 해제된 뒤에도 이만큼 더 진정을 계속합니다(한계선에서 멈추지 않음). 0 = 즉시 중지.", SCRIERS_GAZE),
		["pt-br"] = string.format("Continua dissipando por este tempo depois que o PERIGO (ou o ponto de dissipação de %s) acaba, em vez de parar no limite. 0 = parar imediatamente.", SCRIERS_GAZE),
		["zh-cn"] = string.format("脱离危险（或%s的平息点）后再继续平息这么久，而不是卡在临界点停手。0 = 立即停止。", SCRIERS_GAZE),
		["zh-tw"] = string.format("脫離危險（或%s的平息點）後再繼續平息這麼久，而不是卡在臨界點停手。0 = 立即停止。", SCRIERS_GAZE),
	}),
	auto_plasma_vent = {
		en = "Automatic plasma venting",
		de = "Automatisches Plasma-Entlüften",
		es = "Ventilación automática de plasma",
		fr = "Purge automatique du plasma",
		it = "Sfiato automatico del plasma",
		pl = "Automatyczne wentylowanie plazmy",
		ru = "Автоматическое стравливание плазмы",
		ja = "プラズマ自動排熱",
		ko = "플라즈마 자동 배출",
		["pt-br"] = "Ventilação automática de plasma",
		["zh-cn"] = "等离子枪自动散热",
		["zh-tw"] = "電漿槍自動散熱",
	},
	auto_plasma_vent_description = with_default(WORD_ON, {
		en = "Holds the weapon special to vent Plasma Gun heat while UNSAFE (any class). Venting costs a little health, so it only kicks in when you are about to overheat.",
		de = "Hält bei UNSICHER die Waffen-Spezialfähigkeit, um die Hitze des Plasmagewehrs abzulassen (für jede Klasse). Entlüften kostet etwas Leben und greift daher erst kurz vor der Überhitzung.",
		es = "Mantiene la habilidad especial del arma para ventilar el calor del arma de plasma mientras estés en PELIGRO (cualquier clase). Ventilar cuesta un poco de salud, así que solo se activa cuando estás a punto de sobrecalentarte.",
		fr = "Maintient la capacité spéciale de l'arme pour purger la chaleur du fusil à plasma en état de DANGER (toute classe). La purge coûte un peu de vie, elle ne se déclenche donc qu'au bord de la surchauffe.",
		it = "Tiene premuta l'abilità speciale dell'arma per sfiatare il calore del fucile al plasma quando sei in PERICOLO (qualsiasi classe). Lo sfiato costa un po' di salute, quindi si attiva solo quando stai per surriscaldarti.",
		pl = "Przytrzymuje zdolność specjalną broni, aby wypuścić ciepło karabinu plazmowego w stanie NIEBEZPIECZNIE (dowolna klasa). Wentylowanie kosztuje trochę zdrowia, więc uruchamia się dopiero tuż przed przegrzaniem.",
		ru = "Удерживает особую способность оружия, чтобы стравить жар плазмомёта в состоянии ОПАСНО (любой класс). Стравливание стоит немного здоровья, поэтому срабатывает лишь на грани перегрева.",
		ja = "危険の間、武器のスペシャルを押し続けてプラズマガンの熱を排出します（全クラス）。排熱は体力を少し消費するため、過熱寸前でのみ作動します。",
		ko = "위험 상태일 때 무기 특수 기능을 눌러 플라즈마 건의 열을 배출합니다(모든 직업). 배출은 체력을 조금 소모하므로 과열 직전에만 작동합니다.",
		["pt-br"] = "Segura a habilidade especial da arma para ventilar o calor da arma de plasma enquanto estiver em PERIGO (qualquer classe). Ventilar custa um pouco de vida, então só age quando você está prestes a superaquecer.",
		["zh-cn"] = "处于危险时按住武器特殊操作来散去等离子枪的热量（适用于所有职业）。散热会消耗少量生命，因此仅在即将过热时触发。",
		["zh-tw"] = "處於危險時按住武器特殊操作來散去電漿槍的熱量（適用於所有職業）。散熱會消耗少量生命，因此僅在即將過熱時觸發。",
	}),
	auto_plasma_vent_interrupt = {
		en = "Interrupt on player action",
		de = "Bei Spieleraktion unterbrechen",
		es = "Interrumpir al actuar",
		fr = "Interrompre si vous agissez",
		it = "Interrompi quando agisci",
		pl = "Przerwij przy akcji gracza",
		ru = "Прерывать при действии игрока",
		ja = "プレイヤーの操作で中断",
		ko = "플레이어 행동 시 중단",
		["pt-br"] = "Interromper ao agir",
		["zh-cn"] = "玩家操作时中断",
		["zh-tw"] = "玩家操作時中斷",
	},
	auto_plasma_vent_interrupt_description = with_default(WORD_ON, {
		en = "Stop venting the moment you attack, dodge, use an ability or take any other non-movement action. Moving and looking around never interrupt it.",
		de = "Bricht das Entlüften sofort ab, sobald du angreifst, ausweichst, eine Fähigkeit einsetzt oder eine andere Aktion außer Bewegung ausführst. Bewegen und Umsehen unterbrechen es nie.",
		es = "Deja de ventilar en cuanto atacas, esquivas, usas una habilidad o realizas cualquier otra acción que no sea moverte. Moverte y mirar alrededor nunca lo interrumpen.",
		fr = "Arrête la purge dès que vous attaquez, esquivez, utilisez une capacité ou effectuez toute autre action hors déplacement. Se déplacer et regarder autour ne l'interrompent jamais.",
		it = "Interrompe lo sfiato non appena attacchi, schivi, usi un'abilità o compi qualsiasi altra azione che non sia il movimento. Muoverti e guardarti intorno non lo interrompono mai.",
		pl = "Przerywa wentylowanie w chwili, gdy atakujesz, unikasz, używasz zdolności lub wykonujesz dowolną inną akcję poza ruchem. Poruszanie się i rozglądanie nigdy go nie przerywają.",
		ru = "Прекращает стравливание, как только вы атакуете, уклоняетесь, применяете способность или совершаете любое другое действие, кроме передвижения. Движение и обзор камерой его не прерывают.",
		ja = "攻撃、回避、アビリティ使用など、移動以外の操作をした瞬間に排熱を中断します。移動と視点操作では中断されません。",
		ko = "공격, 회피, 능력 사용 등 이동이 아닌 행동을 하는 순간 배출을 중단합니다. 이동과 시점 조작으로는 중단되지 않습니다.",
		["pt-br"] = "Para de ventilar assim que você ataca, esquiva, usa uma habilidade ou realiza qualquer outra ação que não seja se mover. Mover-se e olhar ao redor nunca o interrompem.",
		["zh-cn"] = "当你攻击、闪避、使用技能或进行任何移动以外的操作时，立即中断散热。移动和转动视角不会中断它。",
		["zh-tw"] = "當你攻擊、閃避、使用技能或進行任何移動以外的操作時，立即中斷散熱。移動和轉動視角不會中斷它。",
	}),
	auto_plasma_vent_hold = {
		en = "Extra vent hold (seconds)",
		de = "Zusätzliches Entlüften (Sekunden)",
		es = "Ventilación adicional (segundos)",
		fr = "Purge supplémentaire (secondes)",
		it = "Sfiato aggiuntivo (secondi)",
		pl = "Dodatkowe wentylowanie (sekundy)",
		ru = "Доп. стравливание (секунды)",
		ja = "追加排熱時間（秒）",
		ko = "추가 배출 시간 (초)",
		["pt-br"] = "Ventilação extra (segundos)",
		["zh-cn"] = "额外散热时长（秒）",
		["zh-tw"] = "額外散熱時長（秒）",
	},
	auto_plasma_vent_hold_description = with_default("0.0", {
		en = "Keep venting this long after UNSAFE clears, instead of stopping at the edge. 0 = stop immediately.",
		de = "Entlüftet nach dem Ende von UNSICHER noch so lange weiter, statt am Limit zu stoppen. 0 = sofort stoppen.",
		es = "Sigue ventilando este tiempo después de dejar de estar en PELIGRO, en vez de parar al borde. 0 = parar de inmediato.",
		fr = "Continue de purger pendant ce délai après la fin du DANGER, au lieu de s'arrêter à la limite. 0 = arrêt immédiat.",
		it = "Continua a sfiatare per questo tempo dopo la fine del PERICOLO, invece di fermarsi al limite. 0 = ferma subito.",
		pl = "Wentyluje jeszcze tak długo po ustaniu stanu NIEBEZPIECZNIE, zamiast zatrzymywać się na krawędzi. 0 = zatrzymaj natychmiast.",
		ru = "Продолжает стравливание столько после снятия ОПАСНО, вместо остановки на грани. 0 = остановиться сразу.",
		ja = "危険が解除された後もこの秒数だけ排熱を続けます（限界ぎりぎりで止めない）。0 = 即座に停止。",
		ko = "위험이 해제된 뒤에도 이만큼 더 배출을 계속합니다(한계선에서 멈추지 않음). 0 = 즉시 중지.",
		["pt-br"] = "Continua ventilando por este tempo depois que o PERIGO acaba, em vez de parar no limite. 0 = parar imediatamente.",
		["zh-cn"] = "脱离危险后再继续散热这么久，而不是卡在临界点停手。0 = 立即停止。",
		["zh-tw"] = "脫離危險後再繼續散熱這麼久，而不是卡在臨界點停手。0 = 立即停止。",
	}),

	-- HUD Indicator
	show_unsafe = {
		en = "Show UNSAFE",
		de = "UNSICHER anzeigen",
		es = "Mostrar PELIGRO",
		fr = "Afficher DANGER",
		it = "Mostra PERICOLO",
		pl = "Pokaż NIEBEZPIECZNIE",
		ru = "Показывать ОПАСНО",
		ja = "「危険」を表示",
		ko = "위험 표시",
		["pt-br"] = "Mostrar PERIGO",
		["zh-cn"] = "显示危险",
		["zh-tw"] = "顯示危險",
	},
	show_unsafe_description = with_default(WORD_ON, {}),
	unsafe_word = {
		en = "UNSAFE word",
		de = "UNSICHER-Wort",
		es = "Palabra PELIGRO",
		fr = "Mot DANGER",
		it = "Parola PERICOLO",
		pl = "Słowo NIEBEZPIECZNIE",
		ru = "Слово ОПАСНО",
		ja = "「危険」の語",
		ko = "위험 단어",
		["pt-br"] = "Palavra PERIGO",
		["zh-cn"] = "危险用词",
		["zh-tw"] = "危險用詞",
	},
	unsafe_word_description = with_default(TXT_UNSAFE, {}),
	unsafe_r = {
		en = "UNSAFE red", de = "UNSICHER Rot", es = "PELIGRO rojo", fr = "DANGER rouge", it = "PERICOLO rosso",
		pl = "NIEBEZPIECZNIE czerwony", ru = "ОПАСНО красный", ja = "危険赤", ko = "위험 빨강",
		["pt-br"] = "PERIGO vermelho", ["zh-cn"] = "危险红", ["zh-tw"] = "危險紅",
	},
	unsafe_r_description = with_default("235", {}),
	unsafe_g = {
		en = "UNSAFE green", de = "UNSICHER Grün", es = "PELIGRO verde", fr = "DANGER vert", it = "PERICOLO verde",
		pl = "NIEBEZPIECZNIE zielony", ru = "ОПАСНО зелёный", ja = "危険緑", ko = "위험 초록",
		["pt-br"] = "PERIGO verde", ["zh-cn"] = "危险绿", ["zh-tw"] = "危險綠",
	},
	unsafe_g_description = with_default("45", {}),
	unsafe_b = {
		en = "UNSAFE blue", de = "UNSICHER Blau", es = "PELIGRO azul", fr = "DANGER bleu", it = "PERICOLO blu",
		pl = "NIEBEZPIECZNIE niebieski", ru = "ОПАСНО синий", ja = "危険青", ko = "위험 파랑",
		["pt-br"] = "PERIGO azul", ["zh-cn"] = "危险蓝", ["zh-tw"] = "危險藍",
	},
	unsafe_b_description = with_default("45", {}),
	show_safe = {
		en = "Show SAFE",
		de = "SICHER anzeigen",
		es = "Mostrar SEGURO",
		fr = "Afficher SÛR",
		it = "Mostra SICURO",
		pl = "Pokaż BEZPIECZNIE",
		ru = "Показывать БЕЗОПАСНО",
		ja = "「安全」を表示",
		ko = "안전 표시",
		["pt-br"] = "Mostrar SEGURO",
		["zh-cn"] = "显示安全",
		["zh-tw"] = "顯示安全",
	},
	show_safe_description = with_default(WORD_OFF, {}),
	safe_word = {
		en = "SAFE word",
		de = "SICHER-Wort",
		es = "Palabra SEGURO",
		fr = "Mot SÛR",
		it = "Parola SICURO",
		pl = "Słowo BEZPIECZNIE",
		ru = "Слово БЕЗОПАСНО",
		ja = "「安全」の語",
		ko = "안전 단어",
		["pt-br"] = "Palavra SEGURO",
		["zh-cn"] = "安全用词",
		["zh-tw"] = "安全用詞",
	},
	safe_word_description = with_default(TXT_SAFE, {}),
	safe_r = {
		en = "SAFE red", de = "SICHER Rot", es = "SEGURO rojo", fr = "SÛR rouge", it = "SICURO rosso",
		pl = "BEZPIECZNIE czerwony", ru = "БЕЗОПАСНО красный", ja = "安全赤", ko = "안전 빨강",
		["pt-br"] = "SEGURO vermelho", ["zh-cn"] = "安全红", ["zh-tw"] = "安全紅",
	},
	safe_r_description = with_default("60", {}),
	safe_g = {
		en = "SAFE green", de = "SICHER Grün", es = "SEGURO verde", fr = "SÛR vert", it = "SICURO verde",
		pl = "BEZPIECZNIE zielony", ru = "БЕЗОПАСНО зелёный", ja = "安全緑", ko = "안전 초록",
		["pt-br"] = "SEGURO verde", ["zh-cn"] = "安全绿", ["zh-tw"] = "安全綠",
	},
	safe_g_description = with_default("220", {}),
	safe_b = {
		en = "SAFE blue", de = "SICHER Blau", es = "SEGURO azul", fr = "SÛR bleu", it = "SICURO blu",
		pl = "BEZPIECZNIE niebieski", ru = "БЕЗОПАСНО синий", ja = "安全青", ko = "안전 파랑",
		["pt-br"] = "SEGURO azul", ["zh-cn"] = "安全蓝", ["zh-tw"] = "安全藍",
	},
	safe_b_description = with_default("70", {}),
	font_size = {
		en = "Font size", de = "Schriftgröße", es = "Tamaño de fuente", fr = "Taille de police", it = "Dimensione del carattere",
		pl = "Rozmiar czcionki", ru = "Размер шрифта", ja = "フォントサイズ", ko = "글꼴 크기",
		["pt-br"] = "Tamanho da fonte", ["zh-cn"] = "字体大小", ["zh-tw"] = "字型大小",
	},
	font_size_description = with_default("42", {}),
	pos_x = {
		en = "Horizontal position", de = "Horizontale Position", es = "Posición horizontal", fr = "Position horizontale",
		it = "Posizione orizzontale", pl = "Pozycja pozioma", ru = "Положение по горизонтали", ja = "水平位置",
		ko = "가로 위치", ["pt-br"] = "Posição horizontal", ["zh-cn"] = "水平位置", ["zh-tw"] = "水平位置",
	},
	pos_x_description = with_default("0", {
		en = "Offset from screen centre. Negative = left, positive = right.",
		de = "Versatz von der Bildschirmmitte. Negativ = links, positiv = rechts.",
		es = "Desplazamiento desde el centro de la pantalla. Negativo = izquierda, positivo = derecha.",
		fr = "Décalage depuis le centre de l'écran. Négatif = gauche, positif = droite.",
		it = "Scostamento dal centro dello schermo. Negativo = sinistra, positivo = destra.",
		pl = "Przesunięcie od środka ekranu. Ujemne = w lewo, dodatnie = w prawo.",
		ru = "Смещение от центра экрана. Отрицательное = влево, положительное = вправо.",
		ja = "画面中央からのずれ。マイナス = 左、プラス = 右。",
		ko = "화면 중앙 기준 오프셋. 음수 = 왼쪽, 양수 = 오른쪽.",
		["pt-br"] = "Deslocamento a partir do centro da tela. Negativo = esquerda, positivo = direita.",
		["zh-cn"] = "相对屏幕中心的偏移。负值 = 向左，正值 = 向右。",
		["zh-tw"] = "相對螢幕中心的偏移。負值 = 向左，正值 = 向右。",
	}),
	pos_y = {
		en = "Vertical position", de = "Vertikale Position", es = "Posición vertical", fr = "Position verticale",
		it = "Posizione verticale", pl = "Pozycja pionowa", ru = "Положение по вертикали", ja = "垂直位置",
		ko = "세로 위치", ["pt-br"] = "Posição vertical", ["zh-cn"] = "垂直位置", ["zh-tw"] = "垂直位置",
	},
	pos_y_description = with_default("200", {
		en = "Offset from screen centre. Negative = up, positive = down.",
		de = "Versatz von der Bildschirmmitte. Negativ = oben, positiv = unten.",
		es = "Desplazamiento desde el centro de la pantalla. Negativo = arriba, positivo = abajo.",
		fr = "Décalage depuis le centre de l'écran. Négatif = haut, positif = bas.",
		it = "Scostamento dal centro dello schermo. Negativo = su, positivo = giù.",
		pl = "Przesunięcie od środka ekranu. Ujemne = w górę, dodatnie = w dół.",
		ru = "Смещение от центра экрана. Отрицательное = вверх, положительное = вниз.",
		ja = "画面中央からのずれ。マイナス = 上、プラス = 下。",
		ko = "화면 중앙 기준 오프셋. 음수 = 위, 양수 = 아래.",
		["pt-br"] = "Deslocamento a partir do centro da tela. Negativo = cima, positivo = baixo.",
		["zh-cn"] = "相对屏幕中心的偏移。负值 = 向上，正值 = 向下。",
		["zh-tw"] = "相對螢幕中心的偏移。負值 = 向上，正值 = 向下。",
	}),

	-- Dropdown option labels. The word presets are also shown on the HUD.
	opt_when_reactive = WORD_REACTIVE,
	opt_when_proactive = WORD_PROACTIVE,
	opt_safe_default = {
		en = "Default (SAFE)", de = "Standard (SICHER)", es = "Predeterminado (SEGURO)", fr = "Par défaut (SÛR)", it = "Predefinito (SICURO)", pl = "Domyślnie (BEZPIECZNIE)",
		ru = "По умолчанию (БЕЗОПАСНО)", ja = "デフォルト（安全）", ko = "기본 (안전)", ["pt-br"] = "Padrão (SEGURO)", ["zh-cn"] = "默认（安全）", ["zh-tw"] = "預設（安全）",
	},
	opt_unsafe_default = {
		en = "Default (UNSAFE)", de = "Standard (UNSICHER)", es = "Predeterminado (PELIGRO)", fr = "Par défaut (DANGER)", it = "Predefinito (PERICOLO)", pl = "Domyślnie (NIEBEZPIECZNIE)",
		ru = "По умолчанию (ОПАСНО)", ja = "デフォルト（危険）", ko = "기본 (위험)", ["pt-br"] = "Padrão (PERIGO)", ["zh-cn"] = "默认（危险）", ["zh-tw"] = "預設（危險）",
	},
	opt_word_cast = {
		en = "CAST", de = "WIRKEN", es = "LANZAR", fr = "LANCER", it = "LANCIA", pl = "RZUĆ",
		ru = "ПРИМЕНИТЬ", ja = "発動", ko = "발동", ["pt-br"] = "CONJURAR", ["zh-cn"] = "施放", ["zh-tw"] = "施放",
	},
	opt_word_go = {
		en = "GO", de = "LOS", es = "YA", fr = "GO", it = "VAI", pl = "START",
		ru = "ВПЕРЁД", ja = "ゴー", ko = "진행", ["pt-br"] = "VAI", ["zh-cn"] = "上", ["zh-tw"] = "上",
	},
	opt_word_clear = {
		en = "CLEAR", de = "FREI", es = "LIBRE", fr = "LIBRE", it = "LIBERO", pl = "WOLNE",
		ru = "ЧИСТО", ja = "クリア", ko = "통과", ["pt-br"] = "LIVRE", ["zh-cn"] = "畅通", ["zh-tw"] = "暢通",
	},
	opt_word_ok = {
		en = "OK", de = "OK", es = "OK", fr = "OK", it = "OK", pl = "OK",
		ru = "ОК", ja = "OK", ko = "OK", ["pt-br"] = "OK", ["zh-cn"] = "可以", ["zh-tw"] = "可以",
	},
	opt_word_ready = {
		en = "READY", de = "BEREIT", es = "LISTO", fr = "PRÊT", it = "PRONTO", pl = "GOTOWE",
		ru = "ГОТОВ", ja = "準備完了", ko = "준비", ["pt-br"] = "PRONTO", ["zh-cn"] = "就绪", ["zh-tw"] = "就緒",
	},
	opt_word_blocked = {
		en = "BLOCKED", de = "GESPERRT", es = "BLOQUEADO", fr = "BLOQUÉ", it = "BLOCCATO", pl = "ZABLOKOWANE",
		ru = "ЗАБЛОКИРОВАНО", ja = "ブロック", ko = "차단됨", ["pt-br"] = "BLOQUEADO", ["zh-cn"] = "已拦截", ["zh-tw"] = "已攔截",
	},
	opt_word_dontcast = {
		en = "DON'T CAST", de = "NICHT WIRKEN", es = "NO LANZAR", fr = "NE PAS LANCER", it = "NON LANCIARE", pl = "NIE RZUCAJ",
		ru = "НЕ ПРИМЕНЯТЬ", ja = "発動するな", ko = "발동 금지", ["pt-br"] = "NÃO CONJURAR", ["zh-cn"] = "勿施放", ["zh-tw"] = "勿施放",
	},
	opt_word_stop = {
		en = "STOP", de = "STOPP", es = "ALTO", fr = "STOP", it = "STOP", pl = "STOP",
		ru = "СТОП", ja = "停止", ko = "정지", ["pt-br"] = "PARE", ["zh-cn"] = "停止", ["zh-tw"] = "停止",
	},
	opt_word_danger = {
		en = "DANGER", de = "GEFAHR", es = "PELIGRO", fr = "DANGER", it = "PERICOLO", pl = "NIEBEZPIECZEŃSTWO",
		ru = "ОПАСНО", ja = "危険", ko = "위험", ["pt-br"] = "PERIGO", ["zh-cn"] = "危险", ["zh-tw"] = "危險",
	},
	opt_word_wait = {
		en = "WAIT", de = "WARTEN", es = "ESPERA", fr = "ATTENDS", it = "ATTENDI", pl = "CZEKAJ",
		ru = "ЖДАТЬ", ja = "待機", ko = "대기", ["pt-br"] = "ESPERE", ["zh-cn"] = "等待", ["zh-tw"] = "等待",
	},
	opt_word_hold = {
		en = "HOLD", de = "HALTEN", es = "MANTÉN", fr = "MAINTIENS", it = "FERMO", pl = "WSTRZYMAJ",
		ru = "УДЕРЖИВАТЬ", ja = "ホールド", ko = "보류", ["pt-br"] = "SEGURE", ["zh-cn"] = "稍候", ["zh-tw"] = "稍候",
	},
}
